using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

public enum PedConfigFlags
{
	PED_FLAG_CAN_FLY_THRU_WINDSCREEN = 32,
	PED_FLAG_DIES_BY_RAGDOLL = 33,
	_PED_FLAG_PUT_ON_MOTORCYCLE_HELMET = 35,
	PED_FLAG_NO_COLLISION = 52,
	_PED_FLAG_IS_SHOOTING = 58,
	_PED_FLAG_IS_ON_GROUND = 60,
	PED_FLAG_NO_COLLIDE = 62,
	PED_FLAG_DEAD = 71,
	PED_FLAG_IS_SNIPER_SCOPE_ACTIVE = 72,
	PED_FLAG_SUPER_DEAD = 73,
	_PED_FLAG_IS_IN_AIR = 76,
	PED_FLAG_IS_AIMING = 78,
	PED_FLAG_DRUNK = 100,
	_PED_FLAG_IS_NOT_RAGDOLL_AND_NOT_PLAYING_ANIM = 104,
	PED_FLAG_NO_PLAYER_MELEE = 122,
	PED_FLAG_NM_MESSAGE_466 = 125,
	PED_FLAG_INJURED_LIMP = 166,
	PED_FLAG_INJURED_LIMP_2 = 170,
	_PED_FLAG_DISABLE_SHUFFLING_TO_DRIVER_SEAT = 184,
	PED_FLAG_INJURED_DOWN = 187,
	PED_FLAG_SHRINK = 223,
	PED_FLAG_MELEE_COMBAT = 224,
	_PED_FLAG_IS_ON_STAIRS = 253,
	_PED_FLAG_HAS_ONE_LEG_ON_GROUND = 276,
	PED_FLAG_NO_WRITHE = 281,
	PED_FLAG_FREEZE = 292,
	PED_FLAG_IS_STILL = 301,
	PED_FLAG_NO_PED_MELEE = 314,
	_PED_SWITCHING_WEAPON = 331,
	PED_FLAG_ALPHA = 410,
	_PED_FLAG_DISABLE_STARTING_VEH_ENGINE = 429,
};